name: Demo Smoke (RB deep + DevOps)
on:
  push: { branches: [ main ] }
  pull_request:
    paths:
      - "scripts/**"
      - "docker-compose.yml"
      - ".env.example"
      - ".github/workflows/demo_smoke.yml"
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create env
        run: cp .env.example .env
      - name: Compose up
        run: docker compose up --build -d
      - name: Wait for health
        run: for i in {1..30}; do curl -fsS localhost:8765/health && exit 0; sleep 3; done; exit 1
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: RB Deep Demo
        run: bash ./scripts/demo_rb_deep.sh
      - name: DevOps Demo
        run: bash ./scripts/demo_devops.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: { name: demo-artifacts, path: "workspace/exports/**\nworkspace/audit/**" }